"""
Utility functions
"""
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn')


def drawCDF(data, label='$x$', max_p=1):
    """Draw CDF plot

    Args:
        data: list-like data structure containing data points
        label: string for the x label
"""
    y = np.linspace(0, max_p, len(data), endpoint=False)
    x = sorted(data)
    plt.plot(x, y)
    plt.xlabel(label)
    plt.ylabel("$p$")
    plt.grid(True)
    plt.show()

def roundList(data, precision = 0):
    """Round the number in a list to a precision

    Args:
        data: list-like data structure containing float
        precision: the precision after the decimal point
"""
    return [round(d, precision) for d in data]


def getFlowMap(log_file, output):
    """Copy the flow-port mapping generated by network simulation to a csv file. This function is needed to get the mapping between the flow ID and the port number. The port number for each flow is unique in ns3-simulator.

    Args:
        log_file: the file path to read the log where containing the mapping data
        output: the output file path

    """
    with open(output, 'w') as of:
        with open(log_file, 'r') as f:
            line = f.readline().strip()
            # By default the mapping start with "Flow_ID,Port"
            while line and not line.startswith("Flow_ID,Port"):
                line = f.readline().strip()

            # "\n\n" will mark the end of the mapping data
            while line:
                of.write(line + "\n")
                line = f.readline().strip()

